config/routes.rb
RpsGame::Application.routes.draw do
  resource :game, :only => [ :new, :show, :create ]
  
  resources :moves, :only => [ :new ]
  
  with_options :to => 'moves#create' do |routes|
    routes.get 'moves/rock', :move => 'rock'
    routes.get 'moves/paper', :move => 'paper'
    routes.get 'moves/scissors', :move => 'scissors'
  end
  
  root :to => 'games#new'
  

end

app/models/game.rb
class Game < ActiveRecord::Base
  attr_accessible :num_rounds, :theme
  
  validates :num_rounds, :theme, :presence => true
  
  has_many :rounds
  
  ROUNDS = 3
  
  def number_of_rounds
    ROUNDS
  end
  
  def current_round_number
    rounds.count
  end
  
  def actual_round_number
    rounds.where("winner != ?", 'tie').count
  end
  
  def wins_for(player)
    rounds.where(:winner => player).count
  end
  
  def ties
    rounds.where(:winner => 'tie').count
  end
  
  def total_moves_for(player, move)
    rounds.where("#{player}_move" => move).count
  end
  
  def game_winner_number
    if wins_for('player1') > wins_for('player2')
      1
    elsif wins_for('player1') < wins_for('player2')
      2
    else
      0
    end
  end
  
  def over?
    actual_round_number < number_of_rounds
  end
end

app/models/round.rb
class Round < ActiveRecord::Base
  attr_accessible :player1_move, :player2_move, :game_id
  
  validates :game_id, :presence => true

  before_save :store_winner, :if => :round_over?
  
  belongs_to :game
  
  def self.latest
    order('created_at DESC').first
  end
  
  def round_over?
    player1_move? && player2_move?
  end
  
  def determine_winner
    WinnerDeterminer.new(player1_move, player2_move).winning_player_number
  end
  
  private
  
  def store_winner
    if determine_winner == 1
      self.winner = 'player1'
    elsif determine_winner == 2
      self.winner = 'player2'
    else
      self.winner = 'tie'
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  helper_method :current_game
  
  protected
  
  def current_game
    @current_game ||= Game.find_by_id(session[:current_game_id])
  end
  
  def current_round
    current_game.rounds.latest
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def new
    @game = Game.new
  end
  
  def show
    @game = Game.find(session[:current_game_id])
  end
  
  def create
    @game = Game.create(params[:game])
    session[:current_game_id] = @game.id
    redirect_to new_move_url
  end
end

app/controllers/moves_controller.rb
class MovesController < ApplicationController
  def new
    current_game.rounds.create
  end
  
  def create
    current_game.rounds.latest.update_attributes(:player1_move => params[:move], 
                                                 :player2_move => move_for_ai)
  end
  
  private
  
  def move_for_ai
    [ 'rock', 'paper', 'scissors' ].sample
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/games/new.html.erb
<%= form_for @game, :url => game_path, :html => {:class => 'form-horizontal' } do |form| %>
  <% if @game.errors.present? %>
    <ul>
      <% @game.errors.full_messages.each do |error| %>
        <li><%= error %></li>
      <% end %>
    </ul>
  <% end %>
  
  <%= form.select(:num_rounds, [[3, 1, {:num_rounds => 3}], 
                                                   [5, 2, {:num_rounds => 5}], 
                                                   [7, 3, {:num_rounds => 7}], 
                                                   [9, 4, {:num_rounds => 9}], 
                                                   [11, 5, {:num_rounds => 11}]])%>
  <br>
  <%= form.select(:theme, [['classic', 1, {:theme => 'classic'}]])%>
  
  <br>
  <%= form.submit "New Game" %>
<% end %>

app/views/games/show.html.erb
Player1 Wins: <%= current_game.wins_for('player1') %>
Ties: <%= current_game.ties %>
Player2 Wins: <%= current_game.wins_for('player2') %>
<br>
<% if current_game.game_winner_number != 0 %>
  Player <%= current_game.game_winner_number %> Wins!
<% else %>
  It's a TIE!
<% end %>
<br>

Player 1 chose rock <%= current_game.total_moves_for('player1', 'rock')%> times | 
Player 2 chose rock <%= current_game.total_moves_for('player2', 'rock')%> times
<br>
Player 1 chose paper <%= current_game.total_moves_for('player1', 'paper')%> times | 
Player 2 chose paper <%= current_game.total_moves_for('player2', 'paper')%> times
<br>
Player 1 chose scissors <%= current_game.total_moves_for('player1', 'scissors')%> times | 
Player 2 chose scissors <%= current_game.total_moves_for('player2', 'scissors')%> times
<br>

<%= button_to("New Game", game_path) %>
<%= link_to "Home", new_game_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RpsGame</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/moves/create.html.erb
Round <%= "#{current_game.actual_round_number}/#{current_game.number_of_rounds}" %>
<br>

Player1 Wins: <%= current_game.wins_for('player1') %>
Ties: <%= current_game.ties %>
Player2 Wins: <%= current_game.wins_for('player2') %>

<% if current_game.over? %>
  <%= link_to "Continue", new_move_path %>
<% else %>
  <%= link_to "Results", game_path %>
<% end %>

app/views/moves/new.html.erb
<% if @move == nil %>
  <%= link_to "Rock", moves_rock_path %>
  <%= link_to "Paper", moves_paper_path %>
  <%= link_to "Scissors", moves_scissors_path %>
<% end %>